FROM ubuntu:16.10
MAINTAINER juliandondero@gmail.com

RUN useradd -ms /bin/bash user
USER user
WORKDIR /home/user
ENV NODE_VERSION 6.8.0
ENV DEBIAN_FRONTEND=noninteractive

USER root

# supervisord from ubuntu repository
RUN apt-get update && apt-get install -y supervisor
RUN apt-get install -y apt-utils
RUN apt-get install -y git-core
RUN apt-get install -y ca-certificates
RUN apt-get install -y ssh
RUN apt-get install -y curl
RUN apt-get install -y vim
RUN apt-get install -y automake
RUN apt-get install -y autoconf
RUN apt-get install -y build-essential
RUN apt-get install -y python-dev

COPY ./scripts/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN git clone https://github.com/facebook/watchman.git && \
	cd watchman && \
	git checkout v4.7.0 && \
	./autogen.sh && \
	./configure && \
	make && \
	make install
	
ADD ssh/ /home/user/.ssh/
RUN chmod 600 /home/user/.ssh/*
RUN ssh-keyscan -p2200 github.com > /home/user/.ssh/known_hosts
RUN chown user:user /home/user/.ssh/*

USER user
WORKDIR /home/user

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash \ 
	&& /bin/bash -c "source ~/.bashrc && source /home/user/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION && nvm use default && npm install bower -g && npm install -g ember-cli && npm install -g less"

USER root
CMD ["/usr/bin/supervisord"]
