FROM ubuntu:17.04
MAINTAINER juliandondero@gmail.com

RUN useradd -ms /bin/bash user
USER user
WORKDIR /home/user
ENV NODE_VERSION 6.10.3
ENV DEBIAN_FRONTEND=noninteractive
ENV ANDROID_HOME=/opt/android-sdk-linux
USER root

# supervisord from ubuntu repository
RUN apt-get update && apt-get install -y supervisor
RUN apt-get install -y apt-utils
RUN apt-get install -y git-core
RUN apt-get install -y ca-certificates
RUN apt-get install -y ssh
RUN apt-get install -y curl
RUN apt-get install -y vim
RUN apt-get install -y automake
RUN apt-get install -y autoconf
RUN apt-get install -y build-essential
RUN apt-get install -y python-dev
RUN apt-get install -y software-properties-common
RUN apt-get update -qq \
    && apt-get install -y openjdk-8-jdk wget expect unzip vim \
    && apt-get clean


COPY ./scripts/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN git clone https://github.com/facebook/watchman.git && \
	cd watchman && \
	git checkout v4.7.0 && \
	./autogen.sh && \
	./configure && \
	make && \
	make install
	
ADD ssh/ /home/user/.ssh/
RUN chmod 600 /home/user/.ssh/*
RUN ssh-keyscan github.com > /home/user/.ssh/known_hosts
RUN chown user:user /home/user/.ssh/*

# Install Java.
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

USER user
WORKDIR /home/user

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash \ 
	&& /bin/bash -c "source ~/.bashrc && source /home/user/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION && nvm use default && npm install npm@latest -g && npm install bower -g && npm install -g ember-cli && npm install -g less && npm install -g cordova@6.5.0"

ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

USER root

# --- Download Android SDK tools into $ANDROID_SDK_HOME

# RUN useradd -u 1000 -M -s /bin/bash user
RUN chown 1000 /opt

COPY tools /opt/tools

COPY licenses /opt/licenses

RUN mkdir -p /opt/android-sdk-linux

RUN "/opt/tools/android-sdk-update.sh"

CMD ["/usr/bin/supervisord"]

